openapi: 3.1.0
info:
  title: CheapFinder API (with Analytics)
  version: 1.2.0
servers:
  - url: https://localhost:8080
paths:
  /search:
    get:
      operationId: searchCheapest
      summary: Search sources and rank by landed price
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: zip
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
        - in: query
          name: minRating
          schema: { type: number, default: 0 }
        - in: query
          name: minReviews
          schema: { type: integer, default: 0 }
        - in: query
          name: maxPrice
          schema: { type: number, default: 0 }
        - in: query
          name: sources
          schema: { type: string }
      responses:
        "200":
          description: Results
  /events:
    post:
      operationId: recordEvent
      summary: Record an anonymized analytics event (requires user consent client-side)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id: { type: string }
                ts: { type: integer }
                anon_user_id: { type: string }
                event_type: { type: string, enum: ["search","open_raw","open_affiliate","purchase_reported"] }
                q: { type: string }
                zip: { type: string }
                min_rating: { type: number }
                max_price: { type: number }
                source: { type: string }
                product_url: { type: string }
                price: { type: number }
                landed_price: { type: number }
                clicked_affiliate: { type: boolean }
      responses:
        "200":
          description: ok
